server:
  port: 10086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: lv-registry