server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://106.13.115.150:3306/leyou?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Dx123456@
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl